### ISSUE TITLE
nedb max store size?

### ISSUE THREAD

**Issue by simonbarker** [leewinter/log-server#9]
So I think nedb has a max store size of 256MB?

[https://github.com/louischatriot/nedb/issues/476](https://github.com/louischatriot/nedb/issues/476)

We were thinking we store like 2 months of logs on the server (with a network share) from all the apis, so 256 might be a bit low.

Got any ideas? Mongo?

**Comment by leewinter** [comment]
Server side the limit is around 1GB

Browser is around 256 I believe. But yeah it was only intended as a cache really and might need some work to deal with old documents

**Comment by simonbarker** [comment]
ok, kool - I'll add a node-cron job that checks the size every hour or so and trims out the oldest logs
